Add isNodeJs and process getters to cli_pkg/js.dart
google/dart_cli_pkg pull request #143
Opened 2023-09-29 01:29 UTC by Goodwine

Related to https://github.com/sass/sass/issues/3662

2023-09-29 20:01 UTC, nex3 requested changes
As discussed offline, also add checks for this to the browser tests.

2023-09-29 20:01 UTC, nex3 commented on lib/js.dart
> +/// different `process` object in the `window`.
Might be worth putting an example of a case where this is known to happen.

2023-10-03 23:03 UTC, nex3 requested changes
When I suggested adding tests in `browser_library_test`, I meant updating the existing test files to verify that `isNodeJs` returns `false` for them. We specifically want to verify that their bundling strategies don't make it look like they're running under Node.js when we know they aren't.

2023-10-03 23:03 UTC, nex3 commented on lib/js.dart
> +Process? get process => isNodeJs ? _process : null;
We should add a note that if users use this getter, they should add their own dependency on `node_interop` to ensure they get a version that's compatible with their usage.

2023-10-03 23:21 UTC, Goodwine commented on browser_library_test/test/node_js_test.dart
It is actually running in a browser 🤔, just without any other libraries involved. There are tests for running within Node already. I will rename this file to make it less confusing.

![github results showing "dart test -p chrome" list of executed tests which includes this file on testing](https://github.com/google/dart_cli_pkg/assets/2022649/2f4eff9e-d5de-40cd-b3fe-6a1af2b613c3)

I guess it's a good idea to expand `browser_test_shared.dart` to verify none of those libraries would incorrectly return `isNodeJs == true`

2023-10-03 23:21 UTC, Goodwine commented on browser_library_test/test/node_js_test.dart
> +@TestOn('browser')
Moved to the top. That said, `browser` is correct because it does run in the browser. But I did rename it to make it less confusing

2023-10-03 23:26 UTC, nex3 requested changes

2023-10-03 23:26 UTC, nex3 commented on lib/js.dart
> +/// Note: Add a dependency on `node_interop` to ensure you get a version
This should say "if you use this,"

2023-10-03 23:26 UTC, nex3 commented on browser_library_test/test/browser_test_shared.dart
> +  test("process returns 'null'", () {
Nit: empy line between tests

2023-10-03 23:28 UTC, Goodwine commented on browser_library_test/test/browser_test_shared.dart
> +  test("process returns 'null'", () {
oops bad copypasta

2023-10-04 00:10 UTC, nex3 approved these changes

2023-10-05 18:29 UTC, merged